### ISSUE TITLE
future after null-ls archived

### ISSUE THREAD

**Issue by kassio** [semanticart/ruby-code-actions.nvim#1]
Hey there, first of all thanks for this plugin!

It's a shame that I just found this now that I migrated to efmls, since null-ls was archived.

Do you have any future plans for this plugin? Maybe integrate it with efmls? (I'm biased as I already migrated there. 😅)

**Comment by semanticart** [comment]
Hi @kassio, thanks for the kind words.

I don't have any real plans for this at the moment, but I think implementing the two current code actions in efmls is probably pretty trivial.

I'll also mention two things. 

1. [This community-maintained fork of null-ls](https://github.com/nvimtools/none-ls.nvim)  seems viable.
2. [Rubocop itself has a budding language server now](https://docs.rubocop.org/rubocop/usage/lsp.html)

Finally, some shameless self-promotion (😉): I've started a newsletter for exploring language servers @ https://newsletter.semanticart.com/ and there's a few previous posts there you can check out.

Have a great day!

**Comment by kassio** [comment]
Thanks! Appreciate all the links!
